### ISSUE TITLE
Feature Request:  Links to heading or Block

### ISSUE THREAD

**Issue by autonomygaps** [mrjackphil/obsidian-text-expand#13]
It would be great to have the option of linking to the headings in which the search terms occur (`[[Title words#Heading words]]`, or the “blocks” in which they occur `[[Title words^blockcode]]`.

**Comment by mrjackphil** [comment]
@autonomygaps 

Could you add more examples of how it can work?

**Comment by McOussKing** [comment]
@mrjackphil 

I think it would be great to search for all tasks using "- [ ]" and link them, or all blocks with a specific tag (#TW for To write, or #today to review, or some kind of tags to implement spaced repetition). I also like to give some blocks an ID following zettelkasten form (20201215143449) to keep track of when they were created, so it would be great to link all blocks created on 20201215 in one file (notably, a daily note) to review them at the end of the day. The usages are endless.

Also, it is more efficient to embed or link just the part we're interested in instead of the whole document, especially if we've multiple blocks of the same criteria distributed at different places in one long file.

**Comment by Domas-Vaitmonas** [comment]
I second this. Would be reaaaally great.

**Comment by mrjackphil** [comment]
Not exactly the same thing but added `$header` and `$blocks` sequences which can help in some cases. About extraction of the search content - I'll work on that next.

**Comment by mrjackphil** [comment]
@obezzad @Domas-Vaitmonas @autonomygaps Now we can use `$match:header` to include headings that contain results from the search. Will it be helpful?

**Comment by obezzad** [comment]
This looks very interesting.
Would it work for any line or just headings?
I am thinking of the following use case:
$match:"- [x]" for all completed tasks.
$match:"- [ ]" for all remaining ones.

**Comment by mrjackphil** [comment]
@obezzad it should work in this way

\```expander
/^- \[ \].+/
$match
```

so it should find all lines which starts with "- [ ]" and should place them below.

**Comment by obezzad** [comment]
It works now. Thank you so much @mrjackphil!

**Comment by mrjackphil** [comment]
If there any suggestions about this topic - please create another issue with feature description.
