### ISSUE TITLE
Bug for vim Keybindings

### ISSUE THREAD

**Issue by santiyounger** [mrjackphil/obsidian-text-expand#22]
Hey thanks for the awesome plugin. I really enjoy it, but unfortunatly there's a strange bug with vim-mode that doesn't allow me to update searches.

## Example:

I have a search such as this one

![image](https://user-images.githubusercontent.com/51902730/103784578-1e1b5400-5008-11eb-9b47-101bff95ebce.png)

After bringing command pallette > Text expand...

I get this correctly...

![image](https://user-images.githubusercontent.com/51902730/103784624-2e333380-5008-11eb-9a1b-94fe6c4042c5.png)

but if I want to update the search, while using vim keybindings, with the cursor in the search as intructed in the read me I get a strange error

Resulting in this:

which is a search of other files where I've used the plugin

![image](https://user-images.githubusercontent.com/51902730/103784771-5ae74b00-5008-11eb-82b3-8e612c911cf2.png)

# Workaround

In order for searches to be updated properly I need to turn of vim keybidings, but I'd really like to be able to do this with vim-mode since I never use obsidian without it.

## Specs

Obsidian v.0.10.6
Text {{Expand}} 0.6.5
Linux Manjaro

Thanks!

**Comment by mrjackphil** [comment]
@santiyounger Yes, I know this bug. It happens because CodeMirror in Vim mode thinks what current line is above the cursor. 

Another workaround for now is to trigger expander one line below the content. 

Once, I’ll put my hand on refactoring this plugin I’ll definitely will try to fix this one because I’m using Vim mode myself :)

**Comment by santiyounger** [comment]
> @santiyounger Yes, I know this bug. It happens because CodeMirror in Vim mode thinks what current line is above the cursor.
> 
> Another workaround for now is to trigger expander one line below the content.
> 
> Once, I’ll put my hand on refactoring this plugin I’ll definitely will try to fix this one because I’m using Vim mode myself :)

Awesome @mrjackphil  thanks for the amazing work with this plugin. That workaround is a great way to solve this for now thanks!

Looking forward to see more of your great work with Obsidian

Thanks!

**Comment by mrjackphil** [comment]
@santiyounger Should be fixed in v0.7.0. Feel free to reopen the issue if there any problems with it.

**Comment by santiyounger** [comment]
Hey thanks a lot for working on this.

Unfortunatly I'm still having troubles with it 

Here is a screenshot of the error (only the first one seems to be relevant to text expander)

I'll look into the other errors it could be a conflcit with other plugins
![image](https://user-images.githubusercontent.com/51902730/109186225-b3141100-775e-11eb-8059-db605d8182d5.png)

Here's the log of the console as well if it helps!
[error-tex-expander.log](https://github.com/mrjackphil/obsidian-text-expand/files/6044479/error-tex-expander.log)

Thanks!

**Comment by mrjackphil** [comment]
@santiyounger Thanks for the feedback. The latest 0.7.1 release should fix this error.

I want to point out what this error was caused by not finding queries on the page. The default behavior of the text expander was changed.

Now you should manually wrap search query without curly brackets by `expander` code block:
```
    ```expander
    SEARCH_QUERY
    ```
```

After that, you can run the `Text expand` command and it should find the closest wrapped block and expand it.

Just to clarify:
- Using curly brackets was deprecated
- Automatic line wrapping was deprecated

**Comment by santiyounger** [comment]
Thanks a lot for all the hard work to fix this. It works perfect now!

Really appreciate it, it's an amazing plugin and the issues with vim where the only thing stopping me from using it more. Now I'll be using it all the time!

Thanks a lot!
